export const list_Menu = [
    {
        mName:'Checkin',
        IconName:'check',
        mID:'checkIn',
        routerName:'profile'
    },
    {
        mName:'Schedule',
        IconName:'edit',
        mID:'schedule',
        routerName:'schedule'
    },
    {
        mName:'Parties',
        IconName:'group',
        mID:'parties',
        routerName:'parties'
    },
    {
        mName:'News',
        IconName:'newspaper-o',
        mID:'news',
        routerName:''
    },
    {
        mName:'Speech',
        IconName:'microphone',
        mID:'speech',
        routerName:''
    },
    {
        mName:'Product',
        IconName:'windows',
        mID:'product',
        routerName:''
    },
    {
        mName:'Location',
        IconName:'location-arrow',
        mID:'location',
        routerName:''
    },
    {
        mName:'Survey',
        IconName:'hand-paper-o',
        mID:'survey',
        routerName:''
    }
]