//APP
export const RESET_APPSTATE = "RESET_APPSTATE";
//Fetch API
export const FETCH_CATCH = "FETCH_CATCH";
//authen
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_EROR = "LOGIN_EROR";
export const LOGING = "LOGING";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const EXPORT_FORM = "EXPORT_FORM";
export const AUTHEN_EXPRI = "AUTHEN_EXPRI";
//register
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_EROR = "REGISTER_EROR";
export const REGISTING = "REGISTING";
export const REGISTER_CLEAR = "REGISTER_CLEAR";
export const DEFAULT = "DEFAULT";
//QUICK actions
export const Presentation = "Presentation";
export const SEARCHING_MUSEUM = "SEARCHING_MUSEUM";
export const Presentation_ERROR = "Presentation_ERROR";
export const Presentation_CLEAR_ERROR = "Presentation_CLEAR_ERROR";
//Hot News actions
export const SEARCH_HOT_NEWS = "SEARCH_HOT_NEWS";
export const SEARCHING_HOT_NEWS = "SEARCHING_HOT_NEWS";
export const SEARCH_HOT_NEWS_ERROR = "SEARCH_HOT_NEWS_ERROR";
export const SEARCH_HOT_NEWS_CLEAR_ERROR = "SEARCH_HOT_NEWS_CLEAR_ERROR";
//check checkin
export const SEARCH_CHECK_CHECKIN = "SEARCH_CHECK_CHECKIN";
export const SEARCHING_CHECK_CHECKIN = "SEARCHING_CHECK_CHECKIN";
export const SEARCH_CHECK_CHECKIN_ERROR = "SEARCH_CHECK_CHECKIN_ERROR";
export const SEARCH_CHECK_CHECKIN_CLEAR_ERROR = "SEARCH_CHECK_CHECKIN_CLEAR_ERROR";
//MAP
export const MAP_ALL = "MAP_ALL";
export const MAP_SEARCHING_ALL = "MAP_SEARCHING_ALL";
export const MAP_ALL_ERROR = "MAP_ALL_ERROR";
export const MAP_ALL_CLEAR_ERROR = "MAP_ALL_CLEAR_ERROR";
//Map Detail
export const MAP_DETAIL_ALL = "MAP_DETAIL_ALL";
export const MAP_DETAIL_SEARCHING_ALL = "MAP_DETAIL_SEARCHING_ALL";
export const MAP_DETAIL_ALL_ERROR = "MAP_DETAIL_ALL_ERROR";
export const MAP_DETAIL_ALL_CLEAR_ERROR = "MAP_DETAIL_ALL_CLEAR_ERROR";
//NOTIFICATION
export const NOTIFICATION_ALL = "NOTIFICATION_ALL";
export const NOTIFICATION_SEARCHING_ALL = "NOTIFICATION_SEARCHING_ALL";
export const NOTIFICATION_ALL_ERROR = "NOTIFICATION_ALL_ERROR";
export const NOTIFICATION_ALL_CLEAR_ERROR = "NOTIFICATION_ALL_CLEAR_ERROR";
//SURVEY
export const SURVEY_ALL = "SURVEY_ALL";
export const SURVEY_SEARCHING_ALL = "SURVEY_SEARCHING_ALL";
export const SURVEY_ALL_ERROR = "SURVEY_ALL_ERROR";
export const SURVEY_ALL_CLEAR_ERROR = "SURVEY_ALL_CLEAR_ERROR";
//PRODUCT_ALL
export const PRODUCT_ALL = "PRODUCT_ALL";
export const PRODUCT_SEARCHING_ALL = "PRODUCT_SEARCHING_ALL";
export const PRODUCT_ALL_ERROR = "PRODUCT_ALL_ERROR";
export const PRODUCT_ALL_CLEAR_ERROR = "PRODUCT_ALL_CLEAR_ERROR";
//PRODUCT_DETAIL_ALL
export const PRODUCT_DETAIL_ALL = "PRODUCT_DETAIL_ALL";
export const PRODUCT_DETAIL_SEARCHING_ALL = "PRODUCT_DETAIL_SEARCHING_ALL";
export const PRODUCT_DETAIL_ALL_ERROR = "PRODUCT_DETAIL_ALL_ERROR";
export const PRODUCT_DETAIL_ALL_CLEAR_ERROR = "PRODUCT_DETAIL_ALL_CLEAR_ERROR";
//News actions
export const SEARCH_NEWS = "SEARCH_NEWS";
export const SEARCHING_NEWS = "SEARCHING_NEWS";
export const SEARCH_NEWS_ERROR = "SEARCH_NEWS_ERROR";
export const SEARCH_NEWS_CLEAR_ERROR = "SEARCH_NEWS_CLEAR_ERROR";
//new Details
export const SEARCH_NEWS_DETAIL = "SEARCH_NEWS_DETAIL";
export const SEARCHING_NEWS_DETAIL = "SEARCHING_NEWS_DETAIL";
export const SEARCH_NEWS_DETAIL_ERROR = "SEARCH_NEWS_DETAIL_ERROR";
export const SEARCH_NEWS_DETAIL_CLEAR_ERROR = "SEARCH_NEWS_DETAIL_CLEAR_ERROR";
//new Details
export const SEARCH_PRESENTATION_DETAIL = "SEARCH_PRESENTATION_DETAIL";
export const SEARCHING_PRESENTATION_DETAIL = "SEARCHING_PRESENTATION_DETAIL";
export const SEARCH_PRESENTATION_DETAIL_ERROR = "SEARCH_PRESENTATION_DETAIL_ERROR";
export const SEARCH_PRESENTATION_DETAIL_CLEAR_ERROR = "SEARCH_PRESENTATION_DETAIL_CLEAR_ERROR";
//Schedule DETAIL
export const SEARCH_Schedule_ERROR="SEARCH_Schedule_ERROR";
export const SEARCH_Schedule_CLEAR_ERROR="SEARCH_Schedule_CLEAR_ERROR"
export const SEARCHING_Schedule="SEARCHING_Schedule";
export const SEARCH_Schedule="SEARCH_Schedule";

//PARTIES
export const SEARCH_PARTIES = "SEARCH_PARTIES";
export const SEARCHING_PARTIES = "SEARCHING_PARTIES";
export const SEARCH_PARTIES_ERROR = "SEARCH_PARTIES_ERROR";
export const SEARCH_PARTIES_CLEAR_ERROR = "SEARCH_PARTIES_CLEAR_ERROR";
//PRESENTATION
export const SEARCH_PRESENTATION = "SEARCH_PRESENTATION";
export const SEARCHING_PRESENTATION = "SEARCHING_PRESENTATION";
export const SEARCH_PRESENTATION_ERROR = "SEARCH_PRESENTATION_ERROR";
export const SEARCH_PRESENTATION_CLEAR_ERROR = "SEARCH_PRESENTATION_CLEAR_ERROR";
//GUESTS
export const SEARCH_GUESTS = "SEARCH_GUESTS";
export const SEARCHING_GUESTS = "SEARCHING_GUESTS";
export const SEARCH_GUESTS_ERROR = "SEARCH_GUESTS_ERROR";
export const SEARCH_GUESTS_CLEAR_ERROR = "SEARCH_GUESTS_CLEAR_ERROR";
//MAPID DETAIL
export const SEARCH_MAPID_DETAIL = "SEARCH_MAPID_DETAIL";
export const SEARCHING_MAPID_DETAIL = "SEARCHING_MAPID_DETAIL";
export const SEARCH_MAPID_DETAIL_ERROR = "SEARCH_MAPID_DETAIL_ERROR";
export const SEARCH_MAPID_DETAIL_CLEAR_ERROR = "SEARCH_MAPID_DETAIL_CLEAR_ERROR";
//ANTIFACT By tag
export const SEARCH_ANTIFACT_BY_TAG = "SEARCH_ANTIFACT_BY_TAG";
export const SEARCHING_ANTIFACT_BY_TAG = "SEARCHING_ANTIFACT_BY_TAG";
export const SEARCH_ANTIFACT_BY_TAG_ERROR = "SEARCH_ANTIFACT_BY_TAG_ERROR";
export const SEARCH_ANTIFACT_BY_TAG_CLEAR_ERROR = "SEARCH_ANTIFACT_BY_TAG_CLEAR_ERROR";
//ANTIFACT BY UUID
export const SEARCH_ANTIFACT_BY_UUID = "SEARCH_ANTIFACT_BY_UUID";
export const SEARCHING_ANTIFACT_BY_UUID = "SEARCHING_ANTIFACT_BY_UUID";
export const SEARCH_ANTIFACT_BY_UUID_ERROR = "SEARCH_ANTIFACT_BY_UUID_ERROR";
export const SEARCH_ANTIFACT_BY_UUID_CLEAR_ERROR = "SEARCH_ANTIFACT_BY_UUID_CLEAR_ERROR";
//CHECKIN BY QRCODE
export const SEARCH_CHECKIN_BY_QRCODE = "SEARCH_CHECKIN_BY_QRCODE";
export const SEARCHING_CHECKIN_BY_QRCODE = "SEARCHING_CHECKIN_BY_QRCODE";
export const SEARCH_CHECKIN_BY_QRCODE_ERROR = "SEARCH_CHECKIN_BY_QRCODE_ERROR";
export const SEARCH_CHECKIN_BY_QRCODE_CLEAR_ERROR = "SEARCH_CHECKIN_BY_QRCODE_CLEAR_ERROR";
export const CHECKED_BY_QRCODE = "CHECKED_BY_QRCODE";
//PRODUCT BY QRCODE

export const GETTING_PRODUCT_BY_QRCODE = "GETTING_PRODUCT_BY_QRCODE";
export const GETTING_PRODUCT_BY_QRCODE_ERROR = "GETED_PRODUCT_BY_QRCODE_ERROR";
export const CLEAR_SEARCH_PRODUCT_BY_QRCODE = "CLEAR_SEARCH_PRODUCT_BY_QRCODE";
export const SEARCH_PRODUCT_BY_QRCODE = "SEARCH_PRODUCT_BY_QRCODE";

//search artifact actions
export const QUICK_SEARCH_ANTIFACT = "QUICK_SEARCH_ANTIFACT";
export const QUICK_SEARCHING_ANTIFACT = "QUICK_SEARCHING_ANTIFACT";
export const QUICK_SEARCH_ANTIFACT_ERROR = "QUICK_SEARCH_ANTIFACT_ERROR";
export const QUICK_SEARCH_ANTIFACT_CLEAR_ERROR = "QUICK_SEARCH_ANTIFACT_CLEAR_ERROR";

//comment actions
export const SEARCH_COMMENT = "SEARCH_COMMENT";
export const SEARCHING_COMMENT = "SEARCHING_COMMENT";
export const SEARCH_COMMENT_ERROR = "SEARCH_COMMENT_ERROR";
export const SEARCH_COMMENT_CLEAR_ERROR = "SEARCH_COMMENT_CLEAR_ERROR";
//save comment
export const SAVED_COMMENT = "SAVED_COMMENT";
export const SAVING_COMMENT = "SAVING_COMMENT";
export const SAVE_COMMENT_ERROR = "SAVE_COMMENT_ERROR";
export const SAVE_COMMENT_CLEAR_ERROR = "SAVE_COMMENT_CLEAR_ERROR";

//question actions
export const SEARCH_QUESTION = "SEARCH_QUESTION";
export const SEARCHING_QUESTION = "SEARCHING_QUESTION";
export const SEARCH_QUESTION_ERROR = "SEARCH_QUESTION_ERROR";
export const SEARCH_QUESTION_CLEAR_ERROR = "SEARCH_QUESTION_CLEAR_ERROR";

//save SUBMIT QUESTION
export const SAVED_SUBMIT_QUESTION = "SAVED_SUBMIT_QUESTION";
export const SAVING_SUBMIT_QUESTION = "SAVING_SUBMIT_QUESTION";
export const SAVE_SUBMIT_QUESTION_ERROR = "SAVE_SUBMIT_QUESTION_ERROR";
export const SAVE_SUBMIT_QUESTION_CLEAR_ERROR = "SAVE_SUBMIT_QUESTION_CLEAR_ERROR";